/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LearnRouteRouteImport } from './routes/learn/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PhoneReplacedRouteImport } from './routes/phone-replaced'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PublicRouteImport } from './routes/public'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as RequestAccessRouteImport } from './routes/request-access'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SharedCodeRouteImport } from './routes/shared-code'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as AdminExamplesRouteImport } from './routes/admin.examples'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminToolsRouteImport } from './routes/admin.tools'
import { Route as ApiSkrillStatusRouteImport } from './routes/api/skrill-status'
import { Route as AuthorWhatsappRouteImport } from './routes/author.whatsapp'
import { Route as ClassDayRouteImport } from './routes/class.$day'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as LearnSlugRouteImport } from './routes/learn/$slug'
import { Route as LearnPromptsRouteImport } from './routes/learn/prompts'
import { Route as LearnRoadmapRouteImport } from './routes/learn/roadmap'
import { Route as LearnStudioRouteImport } from './routes/learn/studio'
import { Route as LearnToolsRouteImport } from './routes/learn/tools'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthorWhatsappIdRouteImport } from './routes/author.whatsapp.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRouteRoute = LearnRouteRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneReplacedRoute = PhoneReplacedRouteImport.update({
  id: '/phone-replaced',
  path: '/phone-replaced',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAccessRoute = RequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedCodeRoute = SharedCodeRouteImport.update({
  id: '/shared-code',
  path: '/shared-code',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExamplesRoute = AdminExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AdminRoute,
} as any)
const ApiSkrillStatusRoute = ApiSkrillStatusRouteImport.update({
  id: '/api/skrill-status',
  path: '/api/skrill-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorWhatsappRoute = AuthorWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthorRoute,
} as any)
const ClassDayRoute = ClassDayRouteImport.update({
  id: '/class/$day',
  path: '/class/$day',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRouteRoute,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRouteRoute,
} as any)
const LearnPromptsRoute = LearnPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => LearnRouteRoute,
} as any)
const LearnRoadmapRoute = LearnRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => LearnRouteRoute,
} as any)
const LearnStudioRoute = LearnStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => LearnRouteRoute,
} as any)
const LearnToolsRoute = LearnToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => LearnRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorWhatsappIdRoute = AuthorWhatsappIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthorWhatsappRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/author': typeof AuthorRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/classes': typeof ClassesRoute
  '/earnings': typeof EarningsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/phone-replaced': typeof PhoneReplacedRoute
  '/progress': typeof ProgressRoute
  '/public': typeof PublicRoute
  '/recover': typeof RecoverRoute
  '/request-access': typeof RequestAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shared-code': typeof SharedCodeRoute
  '/signup': typeof SignupRoute
  '/tutor': typeof TutorRoute
  '/admin/examples': typeof AdminExamplesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/tools': typeof AdminToolsRoute
  '/api/skrill-status': typeof ApiSkrillStatusRoute
  '/author/whatsapp': typeof AuthorWhatsappRouteWithChildren
  '/class/$day': typeof ClassDayRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/prompts': typeof LearnPromptsRoute
  '/learn/roadmap': typeof LearnRoadmapRoute
  '/learn/studio': typeof LearnStudioRoute
  '/learn/tools': typeof LearnToolsRoute
  '/learn/': typeof LearnIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/author/whatsapp/$id': typeof AuthorWhatsappIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/author': typeof AuthorRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/classes': typeof ClassesRoute
  '/earnings': typeof EarningsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/phone-replaced': typeof PhoneReplacedRoute
  '/progress': typeof ProgressRoute
  '/public': typeof PublicRoute
  '/recover': typeof RecoverRoute
  '/request-access': typeof RequestAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shared-code': typeof SharedCodeRoute
  '/signup': typeof SignupRoute
  '/tutor': typeof TutorRoute
  '/admin/examples': typeof AdminExamplesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/tools': typeof AdminToolsRoute
  '/api/skrill-status': typeof ApiSkrillStatusRoute
  '/author/whatsapp': typeof AuthorWhatsappRouteWithChildren
  '/class/$day': typeof ClassDayRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/prompts': typeof LearnPromptsRoute
  '/learn/roadmap': typeof LearnRoadmapRoute
  '/learn/studio': typeof LearnStudioRoute
  '/learn/tools': typeof LearnToolsRoute
  '/learn': typeof LearnIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/author/whatsapp/$id': typeof AuthorWhatsappIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/author': typeof AuthorRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/classes': typeof ClassesRoute
  '/earnings': typeof EarningsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/phone-replaced': typeof PhoneReplacedRoute
  '/progress': typeof ProgressRoute
  '/public': typeof PublicRoute
  '/recover': typeof RecoverRoute
  '/request-access': typeof RequestAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shared-code': typeof SharedCodeRoute
  '/signup': typeof SignupRoute
  '/tutor': typeof TutorRoute
  '/admin/examples': typeof AdminExamplesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/tools': typeof AdminToolsRoute
  '/api/skrill-status': typeof ApiSkrillStatusRoute
  '/author/whatsapp': typeof AuthorWhatsappRouteWithChildren
  '/class/$day': typeof ClassDayRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/prompts': typeof LearnPromptsRoute
  '/learn/roadmap': typeof LearnRoadmapRoute
  '/learn/studio': typeof LearnStudioRoute
  '/learn/tools': typeof LearnToolsRoute
  '/learn/': typeof LearnIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/author/whatsapp/$id': typeof AuthorWhatsappIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn'
    | '/account'
    | '/admin'
    | '/author'
    | '/certificate'
    | '/classes'
    | '/earnings'
    | '/home'
    | '/login'
    | '/phone-replaced'
    | '/progress'
    | '/public'
    | '/recover'
    | '/request-access'
    | '/reset-password'
    | '/shared-code'
    | '/signup'
    | '/tutor'
    | '/admin/examples'
    | '/admin/security'
    | '/admin/tools'
    | '/api/skrill-status'
    | '/author/whatsapp'
    | '/class/$day'
    | '/learn/$slug'
    | '/learn/prompts'
    | '/learn/roadmap'
    | '/learn/studio'
    | '/learn/tools'
    | '/learn/'
    | '/api/auth/$'
    | '/author/whatsapp/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/author'
    | '/certificate'
    | '/classes'
    | '/earnings'
    | '/home'
    | '/login'
    | '/phone-replaced'
    | '/progress'
    | '/public'
    | '/recover'
    | '/request-access'
    | '/reset-password'
    | '/shared-code'
    | '/signup'
    | '/tutor'
    | '/admin/examples'
    | '/admin/security'
    | '/admin/tools'
    | '/api/skrill-status'
    | '/author/whatsapp'
    | '/class/$day'
    | '/learn/$slug'
    | '/learn/prompts'
    | '/learn/roadmap'
    | '/learn/studio'
    | '/learn/tools'
    | '/learn'
    | '/api/auth/$'
    | '/author/whatsapp/$id'
  id:
    | '__root__'
    | '/'
    | '/learn'
    | '/account'
    | '/admin'
    | '/author'
    | '/certificate'
    | '/classes'
    | '/earnings'
    | '/home'
    | '/login'
    | '/phone-replaced'
    | '/progress'
    | '/public'
    | '/recover'
    | '/request-access'
    | '/reset-password'
    | '/shared-code'
    | '/signup'
    | '/tutor'
    | '/admin/examples'
    | '/admin/security'
    | '/admin/tools'
    | '/api/skrill-status'
    | '/author/whatsapp'
    | '/class/$day'
    | '/learn/$slug'
    | '/learn/prompts'
    | '/learn/roadmap'
    | '/learn/studio'
    | '/learn/tools'
    | '/learn/'
    | '/api/auth/$'
    | '/author/whatsapp/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnRouteRoute: typeof LearnRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthorRoute: typeof AuthorRouteWithChildren
  CertificateRoute: typeof CertificateRoute
  ClassesRoute: typeof ClassesRoute
  EarningsRoute: typeof EarningsRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PhoneReplacedRoute: typeof PhoneReplacedRoute
  ProgressRoute: typeof ProgressRoute
  PublicRoute: typeof PublicRoute
  RecoverRoute: typeof RecoverRoute
  RequestAccessRoute: typeof RequestAccessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SharedCodeRoute: typeof SharedCodeRoute
  SignupRoute: typeof SignupRoute
  TutorRoute: typeof TutorRoute
  ApiSkrillStatusRoute: typeof ApiSkrillStatusRoute
  ClassDayRoute: typeof ClassDayRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-replaced': {
      id: '/phone-replaced'
      path: '/phone-replaced'
      fullPath: '/phone-replaced'
      preLoaderRoute: typeof PhoneReplacedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-access': {
      id: '/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof RequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-code': {
      id: '/shared-code'
      path: '/shared-code'
      fullPath: '/shared-code'
      preLoaderRoute: typeof SharedCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/examples': {
      id: '/admin/examples'
      path: '/examples'
      fullPath: '/admin/examples'
      preLoaderRoute: typeof AdminExamplesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tools': {
      id: '/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/skrill-status': {
      id: '/api/skrill-status'
      path: '/api/skrill-status'
      fullPath: '/api/skrill-status'
      preLoaderRoute: typeof ApiSkrillStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/whatsapp': {
      id: '/author/whatsapp'
      path: '/whatsapp'
      fullPath: '/author/whatsapp'
      preLoaderRoute: typeof AuthorWhatsappRouteImport
      parentRoute: typeof AuthorRoute
    }
    '/class/$day': {
      id: '/class/$day'
      path: '/class/$day'
      fullPath: '/class/$day'
      preLoaderRoute: typeof ClassDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRouteRoute
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRouteRoute
    }
    '/learn/prompts': {
      id: '/learn/prompts'
      path: '/prompts'
      fullPath: '/learn/prompts'
      preLoaderRoute: typeof LearnPromptsRouteImport
      parentRoute: typeof LearnRouteRoute
    }
    '/learn/roadmap': {
      id: '/learn/roadmap'
      path: '/roadmap'
      fullPath: '/learn/roadmap'
      preLoaderRoute: typeof LearnRoadmapRouteImport
      parentRoute: typeof LearnRouteRoute
    }
    '/learn/studio': {
      id: '/learn/studio'
      path: '/studio'
      fullPath: '/learn/studio'
      preLoaderRoute: typeof LearnStudioRouteImport
      parentRoute: typeof LearnRouteRoute
    }
    '/learn/tools': {
      id: '/learn/tools'
      path: '/tools'
      fullPath: '/learn/tools'
      preLoaderRoute: typeof LearnToolsRouteImport
      parentRoute: typeof LearnRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/whatsapp/$id': {
      id: '/author/whatsapp/$id'
      path: '/$id'
      fullPath: '/author/whatsapp/$id'
      preLoaderRoute: typeof AuthorWhatsappIdRouteImport
      parentRoute: typeof AuthorWhatsappRoute
    }
  }
}

interface LearnRouteRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
  LearnPromptsRoute: typeof LearnPromptsRoute
  LearnRoadmapRoute: typeof LearnRoadmapRoute
  LearnStudioRoute: typeof LearnStudioRoute
  LearnToolsRoute: typeof LearnToolsRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteRouteChildren: LearnRouteRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
  LearnPromptsRoute: LearnPromptsRoute,
  LearnRoadmapRoute: LearnRoadmapRoute,
  LearnStudioRoute: LearnStudioRoute,
  LearnToolsRoute: LearnToolsRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteRouteWithChildren = LearnRouteRoute._addFileChildren(
  LearnRouteRouteChildren,
)

interface AdminRouteChildren {
  AdminExamplesRoute: typeof AdminExamplesRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminToolsRoute: typeof AdminToolsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminExamplesRoute: AdminExamplesRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminToolsRoute: AdminToolsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthorWhatsappRouteChildren {
  AuthorWhatsappIdRoute: typeof AuthorWhatsappIdRoute
}

const AuthorWhatsappRouteChildren: AuthorWhatsappRouteChildren = {
  AuthorWhatsappIdRoute: AuthorWhatsappIdRoute,
}

const AuthorWhatsappRouteWithChildren = AuthorWhatsappRoute._addFileChildren(
  AuthorWhatsappRouteChildren,
)

interface AuthorRouteChildren {
  AuthorWhatsappRoute: typeof AuthorWhatsappRouteWithChildren
}

const AuthorRouteChildren: AuthorRouteChildren = {
  AuthorWhatsappRoute: AuthorWhatsappRouteWithChildren,
}

const AuthorRouteWithChildren =
  AuthorRoute._addFileChildren(AuthorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnRouteRoute: LearnRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthorRoute: AuthorRouteWithChildren,
  CertificateRoute: CertificateRoute,
  ClassesRoute: ClassesRoute,
  EarningsRoute: EarningsRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PhoneReplacedRoute: PhoneReplacedRoute,
  ProgressRoute: ProgressRoute,
  PublicRoute: PublicRoute,
  RecoverRoute: RecoverRoute,
  RequestAccessRoute: RequestAccessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SharedCodeRoute: SharedCodeRoute,
  SignupRoute: SignupRoute,
  TutorRoute: TutorRoute,
  ApiSkrillStatusRoute: ApiSkrillStatusRoute,
  ClassDayRoute: ClassDayRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
